//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoultryCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class diseases_tbl
    {
        public int Id { get; set; }
        public string Flock { get; set; }
        public string diseases { get; set; }
        public string symptoms { get; set; }
        public string Image { get; set; }
        public string Notes { get; set; }
    }
}
