//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoultryCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egg_Collection_tbl
    {
        public long Id { get; set; }
        public string Flock { get; set; }
        public string Collection_Date { get; set; }
        public string Collected_Eggs { get; set; }
        public string Good_Eggs { get; set; }
        public string Spoilt_Eggs { get; set; }
        public string Comment { get; set; }
    }
}
