//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoultryCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farm_Master
    {
        public long Id { get; set; }
        public string Farm_Name { get; set; }
        public string Owner_Name { get; set; }
        public string Contact_person { get; set; }
        public string Addrees { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string date { get; set; }
    }
}
