//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoultryCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flock_Management_tbl
    {
        public long Id { get; set; }
        public string Acquired_On { get; set; }
        public string Flock_Name { get; set; }
        public string Flock_Breed { get; set; }
        public string Flock_Source { get; set; }
        public string Total_Chiken { get; set; }
        public string Chicks { get; set; }
        public string Hens { get; set; }
        public string Cocks { get; set; }
        public string Date { get; set; }
        public string Description { get; set; }
    }
}
