//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoultryCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue_Items_master
    {
        public long Id { get; set; }
        public string Farm_name { get; set; }
        public string Farm_Id { get; set; }
        public string Item_Type { get; set; }
        public string Item_Name { get; set; }
        public Nullable<int> Quentity { get; set; }
        public string Issue_Date { get; set; }
        public string Farm_number { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
