//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoultryCRM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Poultry_CRMEntities : DbContext
    {
        public Poultry_CRMEntities()
            : base("name=Poultry_CRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bird_Issue_master> Bird_Issue_master { get; set; }
        public virtual DbSet<Birds_Master> Birds_Master { get; set; }
        public virtual DbSet<Chiken_Breed_master> Chiken_Breed_master { get; set; }
        public virtual DbSet<Daily_Feeding_tbl> Daily_Feeding_tbl { get; set; }
        public virtual DbSet<diseases_Master> diseases_Master { get; set; }
        public virtual DbSet<diseases_tbl> diseases_tbl { get; set; }
        public virtual DbSet<Egg_Collection_tbl> Egg_Collection_tbl { get; set; }
        public virtual DbSet<Farm_Master> Farm_Master { get; set; }
        public virtual DbSet<FeedType_Master> FeedType_Master { get; set; }
        public virtual DbSet<Flock_Management_tbl> Flock_Management_tbl { get; set; }
        public virtual DbSet<Issue_Items_master> Issue_Items_master { get; set; }
        public virtual DbSet<Login_Reg_tbl> Login_Reg_tbl { get; set; }
        public virtual DbSet<Medication_Master> Medication_Master { get; set; }
        public virtual DbSet<Medication_tbl> Medication_tbl { get; set; }
        public virtual DbSet<Unit_Master> Unit_Master { get; set; }
        public virtual DbSet<Vaccination_tbl> Vaccination_tbl { get; set; }
        public virtual DbSet<Vaccine_Master> Vaccine_Master { get; set; }
    }
}
