//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoultryCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaccination_tbl
    {
        public long Id { get; set; }
        public string Flock { get; set; }
        public string Vaccination_Date { get; set; }
        public string Vaccine { get; set; }
        public string Chiks { get; set; }
    }
}
